version: '3.8'

services:
  spring:
    image: skilled-project:yiyaaa
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
