version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  spring:
    image: skilled-project:yiyaaa
    container_name: skilled_project
    ports:
      - "80:8080"
    depends_on:
      - redis
    networks:
      - skilled-project-net

networks:
  skilled-project-net:
    external: true
